"""Adicionar coluna subcategories na tabela categories

Revision ID: 6bf5c07f1831
Revises: a7103b9777e7
Create Date: 2025-05-24 14:24:38.280561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.custom_types import SQLiteListType


# revision identifiers, used by Alembic.
revision: str = '6bf5c07f1831'
down_revision: Union[str, None] = 'a7103b9777e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('subcategories', SQLiteListType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'subcategories')
    # ### end Alembic commands ###
